### ISSUE TITLE
Ping-From

### ISSUE THREAD

**Issue by annevk** [protocol-registries/http-fields#28]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: Ping-From
* Status: permanent
* Specification document(s): https://html.spec.whatwg.org/multipage/links.html#ping-from
* Comments: N/A

Any additional information (this will not be included in the registry)?

N/A

**Comment by royfielding** [comment]
I think Ping-From should be registered as "deprecated".

**Comment by mnot** [comment]
@annevk ?

**Comment by annevk** [comment]
It's not considered for removal from the HTML Standard (see https://github.com/whatwg/html/labels/removal%2Fdeprecation) and this is the first time I've seen that being suggested.

I'm also not sure what you expect from me here. https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.16.3.1 doesn't give guidance on this and the comment isn't particularly constructive.

**Comment by royfielding** [comment]
I was under the impression that four out of five browsers had already refused to implement, but it looks like a few have just configured it off by default.
