### ISSUE TITLE
Sec-GPC

### ISSUE THREAD

**Issue by darobin** [protocol-registries/http-fields#32]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [ ] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: Sec-GPC
* Status: provisional
* Specification document(s): https://globalprivacycontrol.github.io/gpc-spec/
* Comments:

Any additional information (this will not be included in the registry)?

The document will certainly be moved as the specification moves through the adoption process and the ownership will be transferred to W3C at some point. However, the specification is implemented by several browsers and high-profile web sites, so it feels like registering it sooner rather than later is best.

**Comment by mnot** [comment]
That makes sense. Please keep us informed of any changes in the spec URL.

**Comment by darobin** [comment]
Thanks @mnot!
