### ISSUE TITLE
Register the `Clear-Site-Data` HTTP header

### ISSUE THREAD

**Issue by yoshuawuyts** [protocol-registries/http-fields#33]
Hi, I noticed [`Clear-Site-Data`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data) is currently not tracked in the IETF header tracker. It's implemented in most major browsers, so I assume it probably should be.

I don't want to carry the responsibility of registering the header in the IETF tracker, so instead I'm just opening an issue to notify y'all that it appears to be missing. Perhaps someone else can carry forward an actual proposal to register it. I hope that's helpful, thanks!

**Comment by mnot** [comment]
Pinging @mikewest. I'm closing here - Mike, open a new one using  a template?

**Comment by mikewest** [comment]
Done in https://github.com/protocol-registries/http-fields/issues/34, thanks.
