### ISSUE TITLE
Register `Clear-Site-Data`

### ISSUE THREAD

**Issue by mikewest** [protocol-registries/http-fields#34]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: Clear-Site-Data
* Status: Permanent
* Specification document(s): https://w3c.github.io/webappsec-clear-site-data/#header
* Comments:

Any additional information (this will not be included in the registry)?

/cc @yoshuawuyts

**Comment by mnot** [comment]
Do you want to use the GitHub URL or the w3c one? (there was a recent kerfuffle about GitHub URLs in the W3C, IIRC)

**Comment by mikewest** [comment]
A kerfuffle, you say? Ugh. In that case:

* Field name: Clear-Site-Data
* Status: Permanent
* Specification document(s): https://w3.org/TR/clear-site-data/#header
* Comments:

**Comment by mnot** [comment]
Great, thanks!
