### ISSUE TITLE
Permanent message header field registration for traceparent and tracestate

### ISSUE THREAD

**Issue by plehegar** [protocol-registries/http-fields#35]
* Field name: traceparent
* Status: permanent
* Specification document(s): https://www.w3.org/TR/trace-context/#traceparent-header

* Comments: (none)

* Field name: tracestate
* Status: permanent
* Specification document(s): https://www.w3.org/TR/trace-context/#tracestate-header
* Comments: (none)

This is a follow-up to
https://mailarchive.ietf.org/arch/msg/ietf-message-headers/AUPU45d0Pr30TEjx-yo4hvCwYQw/

**Comment by mnot** [comment]
Note that IANA has used the following URL for tracestate:
  https://www.w3.org/TR/trace-context/#tracestate-header

If that's incorrect, please say so.
