### ISSUE TITLE
Register HTTP Header field for Permissions Policy

### ISSUE THREAD

**Issue by clelland** [protocol-registries/http-fields#38]
Please confirm that:

* [X] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [X] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [X] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: `Permissions-Policy`
* Status: Permanent
* Specification document(s): https://w3c.github.io/webappsec-permissions-policy/
* Comments:

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Hi @clelland -- has this been adopted by the WebAppSec WG (I don't see it on <https://github.com/w3c/webappsec>)? Is it sufficiently mature to register (i.e., is it likely to change before becoming REC)?

If the answers to both are 'yes' I'm happy to register now; if not, it might be good to pause (considering this issue a 'soft' reservation to hold the value).

**Comment by clelland** [comment]
Yes, it has been adopted ([charter link](https://www.w3.org/2022/06/webappsec-charter-2022.html#:~:text=Charter%3A%202015%20charter-,Permissions%20Policy,-A%20mechanism%20that)). The naming has been stable for several years now, and is unlikely to change at this point.

**Comment by mnot** [comment]
Thanks. I'm going to request it be provisionally registered until the document is more mature; when it's a REC (or close to, maybe CR?) ping me and we'll flip it to permanent.

**Comment by mnot** [comment]
(and sorry for the delay; been travelling)
