### ISSUE TITLE
Register HTTP Header field for Reporting Endpoints

### ISSUE THREAD

**Issue by clelland** [protocol-registries/http-fields#39]
Please confirm that:

* [X] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [X] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [X] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: `Reporting-Endpoints`
* Status: Permanent
* Specification document(s): https://w3c.github.io/reporting/#header
* Comments:

Any additional information (this will not be included in the registry)?

**Comment by mnot** [comment]
Hi @clelland -- has this been adopted by the WebAppSec WG (I don't see it on https://github.com/w3c/webappsec)? Is it sufficiently mature to register (i.e., is it likely to change before becoming REC)?

If the answers to both are 'yes' I'm happy to register now; if not, it might be good to pause (considering this issue a 'soft' reservation to hold the value).

**Comment by clelland** [comment]
1. No, it is not a product of WebAppSec, but is adopted by WebPerfWG -- See [charter link](https://www.w3.org/2021/02/webperf.html#:~:text=2018/09/webperf/-,Reporting,-This%20specification%20defines).
2. I believe that this field is stable and unlikely to change at this point.

**Comment by mnot** [comment]
Ah, of course, sorry. Registering as provisional until the spec is more mature; please ping and we'll flip it to permanent once the spec is CR or PR.
