### ISSUE TITLE
Network Error Logging

### ISSUE THREAD

**Issue by clelland** [protocol-registries/http-fields#40]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: NEL
* Status: Permanent
* Specification document(s): https://www.w3.org/TR/network-error-logging/
* Comments:

Any additional information (this will not be included in the registry)?
This field and its syntax have been stable since ~2017

**Comment by mnot** [comment]
I suspect W3C would prefer to use the /TR URI as the reference:
  https://www.w3.org/TR/network-error-logging/

Is that OK?
