### ISSUE TITLE
Requesting addition of the CMCD HTTP Field names

### ISSUE THREAD

**Issue by wilaw** [protocol-registries/http-fields#48]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field names: Common Media Client Data (CMCD) defines four field names:

```
CMCD-Request 
CMCD-Object 
CMCD-Status 
CMCD-Session 
```

* Status: Permanent
* Specification document(s): CTA-5004 Common Media Client Data available at https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5004-final.pdf
* Comments:

Any additional information (this will not be included in the registry)?

CMCD was standardized in Sept 2020 and has seen broad support. Most major players today support CMCD, along with most CDNs.

**Comment by mnot** [comment]
Hi Will,

CTA isn't yet a [recognised SDO](https://www.iana.org/assignments/iesg-recognized-organizations/iesg-recognized-organizations.xhtml#organizations) for the purposes of registration, so we'll make these provisional.
