### ISSUE TITLE
Requesting addition of the CMSD HTTP Field names

### ISSUE THREAD

**Issue by wilaw** [protocol-registries/http-fields#49]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: Common Media Server Data (CMSD) defines 2 field names:

```
CMSD-Static
CMSD-Dynamic
```

* Status: Permanent
* Specification document(s): CTA-5006 Common Media Server Data (CMSD) https://cdn.cta.tech/cta/media/media/resources/standards/pdfs/cta-5006-final.pdf 
* Comments:

Any additional information (this will not be included in the registry)?
CTA-5006 was published in November 2022 and is leveraged by a number of large CDNs.

**Comment by mnot** [comment]
CTA isn't yet a [recognised SDO](https://www.iana.org/assignments/iesg-recognized-organizations/iesg-recognized-organizations.xhtml#organizations) for the purposes of registration, so we'll make these provisional.
