### ISSUE TITLE
Referrer-Policy

### ISSUE THREAD

**Issue by stiiin** [protocol-registries/http-fields#50]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: Referrer-Policy
* Status: provisional
* Specification document(s): https://www.w3.org/TR/referrer-policy/#referrer-policy-header
* Comments: The header name does not share the HTTP Referer header’s misspelling.

Any additional information (this will not be included in the registry)?

This is a third-party request.

I have previously filed [an issue](https://github.com/w3c/webappsec-referrer-policy/issues/168) with the specification's editor signalling the absence of this registration. There was no response to this issue.

I thought it was important to have it registered anyway. The header has been [supported by most browsers for years](https://caniuse.com/referrer-policy). It is also commonly mentioned in security best practices (e.g. by OWASP's [HTTP Security Response Headers Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#referrer-policy)).

I took the comment verbatim from the specification.

**Comment by mnot** [comment]
@plehegar @simoneonofri any thoughts?

**Comment by plehegar** [comment]
My initial thought would be that the header ought to be registered.

**Comment by mnot** [comment]
@plehegar could WebAppSec process their issue (ref'd above)? It's best to have requests come from (or at least authorised by) the group that owns the protocol element, whenever possible.

**Comment by simoneonofri** [comment]
@mnot I agree with @plehegar, I [contacted the group](https://lists.w3.org/Archives/Public/public-webappsec/2024Aug/0003.html) about it, as this week call was cancelled.

**Comment by domfarolino** [comment]
Given https://github.com/w3c/webappsec-referrer-policy/pull/171#issuecomment-2307597050, could we amend the request to be `permanent`, instead of `provisional`?
