### ISSUE TITLE
Add `Accept-Query`

### ISSUE THREAD

**Issue by desiderantes** [protocol-registries/http-fields#51]
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-field-extensibility).
* [x] You have checked [the registry](https://www.iana.org/assignments/http-fields/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information below.

If so, please provide the details of your request below.

* Field name: `Accept-Query`
* Status: `permanent`
* Specification document(s): [IETF Draft](https://datatracker.ietf.org/doc/draft-ietf-httpbis-safe-method-w-body/)
* Comments: 

Any additional information (this will not be included in the registry)? Spec is currently in Draft. Awaiting for RFC status. https://github.com/httpwg/http-extensions/issues/2903

**Comment by mnot** [comment]
This will be processed when the draft progresses in the IETF process.
